### ISSUE TITLE
False negative based on property name

### ISSUE THREAD

**Issue by danielo515** [kitajs/ts-html-plugin#2]
It may sound stupid that  I'm opening an issue that is exactly the opposite as #1 , but I think this is a simpler one.
I think that the checker is taking the name of the property into account when deciding what is safe and what is not.

Here is the example that is having a false positive:

```ts
          <div class={`chat-bubble ${message.fromMe ? 'is-me' : ''}`}>
            <div safe>{message.body}</div> // <- Here is the error
            <footer >
              <span safe>type: {message.type}</span>
              <span safe>id: {message.whatId}</span>
              <span safe>from: {message.from}</span>
            </footer>
          </div>
```

I'm getting this warning: 
``` 
You are using the safe attribute on expressions that does not contain any XSS vulnerabilities. Please remove the safe attribute or prepend your variable with `unsafe`. [17091977]
```

As you can probably deduce from the context, message.body is just a string like type, from and whatId are, exactly the same thing coming from the same object:
```ts
(parameter) message: {
    id: number;
    data: unknown;
    type: string;
    body: string | null;
    whatId: string;
    chat_id: string;
    from: string;
    fromMe: boolean;
    timestamp: number;
    isForwarded: boolean | null;
}
```
I think the name `body` is being interpreted as some kind of dom node or something like that, hence it is not being reported as unsafe.

**Comment by arthurfiorette** [comment]
Hey @danielo515 thanks for your time testing this plugin! Just commited the security fix and will release asap!
